default: &default
  adapter: mysql2

  encoding: utf8
  password: Qazplm!23

  timeout: 5000
  username: root
  

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nav_app
  password: Qazplm!23

